# Global settings
default-lease-time 600;
max-lease-time 7200;
authoritative;

# Network: 192.168.10.0/24
subnet 192.168.10.0 netmask 255.255.255.0 {
    range 192.168.10.100 192.168.10.200;
    option routers 192.168.10.1;
    option subnet-mask 255.255.255.0;
    option domain-name "domain.com";
    option domain-name-servers 192.168.10.1;
}

# Fixed IP for M1
host M1 {
    hardware ethernet 08:00:27:d5:c3:0b;
    fixed-address 192.168.10.11;
}

# Fixed IP for M2
host M2 {
    hardware ethernet 08:00:27:a8:09:48;
    fixed-address 192.168.10.12;
}
